services:
  - type: web
    name: postiz
    env: docker
    plan: free
    autoDeploy: false
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: POSTIZ_ADMIN_PASSWORD
        value: admin
      - key: POSTIZ_SECRET
        value: supersecuresecret
      - key: POSTIZ_PUBLIC_URL
        value: https://postiz-onrender.onrender.com